### ISSUE TITLE
super admin

### ISSUE THREAD

**Issue by boyfromhell** [eminiarts/nova-permissions#1]
on role detail page.
![https://imgur.com/0YJ3Tx5](https://i.imgur.com/0YJ3Tx5.png)
on permission details page
![https://imgur.com/kOXcaj7](https://i.imgur.com/kOXcaj7.png)

**Comment by bajramemini** [comment]
Hello

It used the wrong Role Model. Make sure to update your `config/permission.php` and use the `Eminiarts\NovaPermissions\Role::class` instead.

Will tag it shortly. Then just update and you should be fine.

Regards
