### ISSUE TITLE
Not showing in sidebar

### ISSUE THREAD

**Issue by kentsigurdsen** [eminiarts/nova-permissions#17]
Hello,

I have installed as described, but i don'get a option in the sidebar to manage roles. 

Also ran npm install and npm run dev.

**Comment by DCReddish97** [comment]
Hi,

I had this issues and it took a few hours to solve.
Have you installed the Laravel Permission Library from Spatie?

`composer require spatie/laravel-permission`

The service provider will automatically get registered. Or you may manually add the service provider in your config/app.php file:

```
'providers' => [
    // ...
    Spatie\Permission\PermissionServiceProvider::class,
];
```
You can publish the migration with:

`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="migrations"`

After the migration has been published you can create the role- and permission-tables by running the migrations:

`php artisan migrate`

You can publish the config file with:

`php artisan vendor:publish --provider="Spatie\Permission\PermissionServiceProvider" --tag="config"`


I also had to install vyuldashev/nova-permission.
`composer require vyuldashev/nova-permission`

**Comment by matovu-ronald** [comment]
The above works just fine, once you install spatie/laravel-permissions and vyuldashev/nova-permission

**Comment by kentsigurdsen** [comment]
Thanks guys. Wrote a PR fo requiring nova-permission
