### ISSUE TITLE
  Target class [RolesAndPermissionsSeeder] does not exist.

### ISSUE THREAD

**Issue by zeyadsharo** [eminiarts/nova-permissions#54]
Illuminate\Contracts\Container\BindingResolutionException 

  Target class [RolesAndPermissionsSeeder] does not exist.

  at E:\IMS\vendor\laravel\framework\src\Illuminate\Container\Container.php:811
    807▕ 
    808▕         try {
    809▕             $reflector = new ReflectionClass($concrete);
    810▕         } catch (ReflectionException $e) {
  ➜ 811▕             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
    812▕         }
    813▕
    814▕         // If the type is not instantiable, the developer is attempting to resolve
    815▕         // an abstract type such as an Interface or Abstract Class and there is

  1   E:\IMS\vendor\laravel\framework\src\Illuminate\Container\Container.php:809
      ReflectionException::("Class RolesAndPermissionsSeeder does not exist")

  2   E:\IMS\vendor\laravel\framework\src\Illuminate\Container\Container.php:809
      ReflectionClass::__construct("RolesAndPermissionsSeeder")

**Comment by Nelazsky** [comment]
The same issue

yes, i try  "composer dumpautoload"  )
