### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by hjelmdal** [eminiarts/nova-permissions#6]
Getting an error on: 
```
// in app/Providers/NovaServiceProvider.php

// ...

public function tools()
{
    return [
        // ...
        \Eminiarts\NovaPermissions\NovaPermissions(),
    ];
}
```
Throws:
```
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Eminiarts\NovaPermissions\NovaPermissions()
```

**Comment by bajramemini** [comment]
Hello @hjelmdal 

Did you try `composer dumpautoload` ? 

Not sure why you are getting this error.

Will try to have a look to it tomorrow. 

Regards

**Comment by bajramemini** [comment]
Hello @hjelmdal 

Ok found the error, the Syntax should be:
`new \Eminiarts\NovaPermissions\NovaPermissions(),` with a `new ...`

Sorry for the Error in the Readme.

Let me know if you need more help.

Regards
Bajram
