### ISSUE TITLE
Registering Package Related Policies

### ISSUE THREAD

**Issue by tanmuhittin** [eminiarts/nova-permissions#9]
For navigation to work properly and for the sake of security, policies related to spatie models must be registered in AuthServiceProvider.php I think this should be in Readme.

Example:
'Spatie\Permission\Models\Permission' => 'App\Policies\Policy',
'Spatie\Permission\Models\Role' => 'App\Policies\Policy',

**Comment by bajramemini** [comment]
Thanks @tanmuhittin 

This error came from a pull request. Going to fix it right now. 

Regards
